[package]
name = "awful_text_news"
version = "0.1.2"
edition = "2024"

[dependencies]
awful_aj = { version = "*", git = "https://github.com/graves/awful_aj" }
reqwest = { version = "*", features = ["rustls-tls"] }
scraper = "*"
url = "*"
tokio = { version = "1.33.0", features = ["full"] }
futures = "0.3.31"
serde = { version = "*", features = ["derive"] }
serde_json = "*"
chrono = "0.4.41"
serde_yaml = "0.9.34"
clap = { version = "4.5.37", features = ["derive"] }
